name: Deploy React App to Azure (Self-hosted)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Generate .env file with commit SHA
        run: echo "REACT_APP_BUILD_VERSION=${{ github.sha }}" > .env

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Zip entire project (without exclusions)
        run: zip -r app.zip .

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Deploy React App to Azure Web App
        run: |
          az webapp deploy \
            --resource-group webAppResource \
            --name webAppReact \
            --src-path app.zip
